name: Deploy to One.com

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Deploy to One.com
      uses: rostimelk/one.com-deployer@master
      env:
          ONE_DOMAIN_NAME: eleonoraesau.com
          ONE_SSH_KEY_PUBLIC: ${{ secrets.SHA256:tHJjqQ6THe6RleRWFp0+7pAcydBUeJbj9rkTJhepE/s}}
          ONE_SSH_KEY_PRIVATE: ${{ secrets.SHA256:tHJjqQ6THe6RleRWFp0+7pAcydBUeJbj9rkTJhepE/s}}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
